[package]
name = "immuxsys"
version = "2.0.0"
authors = ["Immux Network Technology Company, Limited"]
edition = "2018"

[dependencies]
# This is a temporary dependency, we currently use clap as a command line tools mainly for testing purpose for now.
clap = "2.33.0"

[dev-dependencies]

[[test]]
name = "test_kv"
path = "src/tests/kv.rs"

