---
port: 3003

# Git
git:
  origin: https://github.com/login
  client_id: 0a3cf9f2c270c6180712
  client_secret: 8166264020dbcce750f0fff255230f9b7525906a
  api: https://api.github.com

secret: immuxcomputesuccess