[package]
name = "immuxsys_dev_utils"
version = "0.2.0"
authors = ["Yiwang Network Technology Company, Limited"]
edition = "2018"

[dependencies]
immuxsys = { path = ".." }
immuxsys_client = { path = "../client" }
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
serde_json = "1.0"